# This is a basic workflow to help you get started with Actions

name: init-site

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  maybe-job-name:
    runs-on: ubuntu-latest
    name: maybe another job name
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: actions/init-simulation-app-action@v1
